name: athena
description: A sample command-line application.
version: 1.0.0
publish_to: none
repository: https://github.com/viniciusamelio/athena

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  frida_query_builder:
    git: https://github.com/viniciusamelio/bt_frida_query_builder.git
  # path: ^1.8.0

dev_dependencies:
  faker: ^2.1.0
  lints: ^2.1.0
  sqlite3: ^2.2.0
  test: ^1.24.0
